import { useMemo, useState } from 'react'

import {
  OUTCOME_KEYS,
  OUTCOME_LABELS,
  OUTCOME_RELIABILITY,
  type BettingLine,
  type OutcomeKey,
  useBettingEdge,
} from '../lib/api/betting'
import { useCurrentTournament } from '../lib/api/tournaments'

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

function formatPct(p: number, decimals = 1): string {
  return `${(p * 100).toFixed(decimals)}%`
}

function formatEdge(edge: number): string {
  const pct = (edge * 100).toFixed(1)
  return edge >= 0 ? `+${pct}%` : `${pct}%`
}

function formatAmerican(odds: number): string {
  return odds >= 0 ? `+${odds}` : `${odds}`
}

// ---------------------------------------------------------------------------
// Price provenance
// ---------------------------------------------------------------------------

// Whether this line was priced against a real sportsbook consensus. Anything
// else was generated by the backend from the served probability itself
// (`_generate_mock_american_odds`: model_prob + sin(field_position) + vig), so
// its "edge" is an artifact of field position and carries no information.
//
// This is a PER-LINE property. The board also carries a single `odds_source`,
// but that reads "datagolf" when *any* one line was real, so it cannot be used
// to describe a row or a market.
//
// A line without a real price is now dropped from the view entirely rather than
// shown with blanked columns: with no market price there is no disagreement to
// display, and a row of dashes only invites the reader to wonder what was
// withheld.
function isRealPrice(line: BettingLine): boolean {
  return line.odds_source === 'datagolf'
}

// Real-price coverage across a market, for the reliability note. Computed from
// the unfiltered board so it describes the market rather than the current view.
function priceCoverage(lines: BettingLine[]): { real: number; total: number } {
  return { real: lines.filter(isRealPrice).length, total: lines.length }
}

// Minimum model-probability filter options for the table. Default is ≥10% so the
// view immediately surfaces meaningful divergences instead of longshot noise,
// while "All" restores the full list.
const PROB_THRESHOLDS: { label: string; value: number }[] = [
  { label: 'All', value: 0 },
  { label: '≥10%', value: 0.1 },
  { label: '≥20%', value: 0.2 },
  { label: '≥30%', value: 0.3 },
]

// ---------------------------------------------------------------------------
// Edge bar chart (custom SVG visualisation)
//
// Renders a horizontal diverging bar chart: positive edge extends right
// (accent colour), negative edge extends left (muted red). The zero line
// sits in the centre so viewers can read both direction and magnitude at a
// glance — a standard viz used by sports-betting analytics teams.
// ---------------------------------------------------------------------------

const BAR_HEIGHT = 16
const BAR_GAP = 6
const CHART_ROW_HEIGHT = BAR_HEIGHT + BAR_GAP
const LABEL_WIDTH = 160
const AXIS_WIDTH = 300 // total half-width (left + right) of chart area
const PADDING = { top: 24, right: 16, bottom: 28, left: 8 }

function EdgeBarChart({ lines, maxEdge }: { lines: BettingLine[]; maxEdge: number }) {
  // Show at most 20 players so the chart stays readable.
  const visible = lines.slice(0, 20)
  const scale = maxEdge > 0 ? (AXIS_WIDTH / 2) / maxEdge : 1

  const svgWidth = LABEL_WIDTH + AXIS_WIDTH + PADDING.left + PADDING.right
  const svgHeight = PADDING.top + visible.length * CHART_ROW_HEIGHT + PADDING.bottom

  const zeroX = PADDING.left + LABEL_WIDTH + AXIS_WIDTH / 2

  return (
    <svg
      width={svgWidth}
      height={svgHeight}
      aria-label="Edge bar chart"
      className="select-none overflow-visible font-mono text-xs"
    >
      {/* zero axis */}
      <line
        x1={zeroX}
        y1={PADDING.top - 8}
        x2={zeroX}
        y2={PADDING.top + visible.length * CHART_ROW_HEIGHT}
        stroke="#232B40"
        strokeWidth={1}
      />

      {/* axis labels */}
      <text
        x={zeroX - AXIS_WIDTH / 2}
        y={PADDING.top - 10}
        textAnchor="middle"
        className="fill-fg-tertiary text-[10px]"
      >
        −{formatEdge(maxEdge).replace('+', '')}
      </text>
      <text x={zeroX} y={PADDING.top - 10} textAnchor="middle" className="fill-fg-tertiary text-[10px]">
        0%
      </text>
      <text
        x={zeroX + AXIS_WIDTH / 2}
        y={PADDING.top - 10}
        textAnchor="middle"
        className="fill-fg-tertiary text-[10px]"
      >
        {formatEdge(maxEdge)}
      </text>

      {visible.map((line, i) => {
        const y = PADDING.top + i * CHART_ROW_HEIGHT
        const barWidth = Math.abs(line.edge) * scale
        // Direction only: the board reads above the market, or below it. Bar
        // colour and weight carry no ranking beyond that — brightening a subset
        // as "actionable" is the recommendation this page no longer makes.
        const above = line.edge >= 0.005
        const fill = above ? '#34A65F' : '#EF4444'
        const opacity = above ? 0.85 : 0.45

        return (
          <g key={line.player_id}>
            {/* player label */}
            <text
              x={PADDING.left + LABEL_WIDTH - 8}
              y={y + BAR_HEIGHT / 2 + 4}
              textAnchor="end"
              className="fill-fg text-[11px]"
            >
              {line.player_name.length > 22
                ? line.player_name.slice(0, 21) + '…'
                : line.player_name}
            </text>

            {/* bar */}
            <rect
              x={above ? zeroX : zeroX - barWidth}
              y={y}
              width={Math.max(barWidth, 2)}
              height={BAR_HEIGHT}
              rx={2}
              fill={fill}
              opacity={opacity}
            />

            {/* edge value label */}
            <text
              x={above ? zeroX + barWidth + 4 : zeroX - barWidth - 4}
              y={y + BAR_HEIGHT / 2 + 4}
              textAnchor={above ? 'start' : 'end'}
              className={`fill-fg-secondary text-[10px]`}
            >
              {formatEdge(line.edge)}
            </text>
          </g>
        )
      })}

      {/* bottom axis ticks */}
      {[-1, -0.5, 0, 0.5, 1].map((frac) => {
        const x = zeroX + frac * (AXIS_WIDTH / 2)
        return (
          <line
            key={frac}
            x1={x}
            y1={PADDING.top + visible.length * CHART_ROW_HEIGHT}
            x2={x}
            y2={PADDING.top + visible.length * CHART_ROW_HEIGHT + 4}
            stroke="#232B40"
            strokeWidth={1}
          />
        )
      })}
    </svg>
  )
}

// ---------------------------------------------------------------------------
// Market selector
// ---------------------------------------------------------------------------

function MarketPicker({
  value,
  onChange,
}: {
  value: OutcomeKey
  onChange: (k: OutcomeKey) => void
}) {
  return (
    <div className="flex flex-wrap gap-2">
      {OUTCOME_KEYS.map((key) => (
        <button
          key={key}
          onClick={() => onChange(key)}
          className={`rounded-full px-3 py-1 text-xs font-medium transition-colors ${
            key === value
              ? 'bg-accent text-white'
              : 'border bg-surface text-fg-secondary hover:text-fg'
          }`}
        >
          {OUTCOME_LABELS[key]}
        </button>
      ))}
    </div>
  )
}

// ---------------------------------------------------------------------------
// Minimum model-probability filter
// ---------------------------------------------------------------------------

function ProbabilityFilter({
  value,
  onChange,
}: {
  value: number
  onChange: (v: number) => void
}) {
  return (
    <div className="flex flex-wrap gap-2">
      {PROB_THRESHOLDS.map((t) => (
        <button
          key={t.value}
          onClick={() => onChange(t.value)}
          className={`rounded-full px-3 py-1 text-xs font-medium transition-colors ${
            t.value === value
              ? 'bg-accent text-white'
              : 'border bg-surface text-fg-secondary hover:text-fg'
          }`}
        >
          {t.label}
        </button>
      ))}
    </div>
  )
}

// ---------------------------------------------------------------------------
// Lines table
// ---------------------------------------------------------------------------

function LinesTable({ lines }: { lines: BettingLine[] }) {
  return (
    <div className="overflow-hidden rounded-lg border">
      <table className="w-full text-sm">
        <thead>
          <tr className="bg-surface-2 text-left text-xs uppercase tracking-wider text-fg-tertiary">
            <th className="w-10 px-4 py-3 text-right">#</th>
            <th className="px-4 py-3">Player</th>
            <th className="px-4 py-3 text-right">Board</th>
            <th className="px-4 py-3 text-right">Implied</th>
            <th className="px-4 py-3 text-right">Odds</th>
            <th className="px-4 py-3">Source</th>
            <th className="px-4 py-3 text-right">Edge</th>
          </tr>
        </thead>
        <tbody className="divide-y">
          {lines.map((line, idx) => {
            // Every row reaching this table has a real book price — the page
            // filters the rest out — so there is no per-row provenance branch
            // left to take. The Source column stays as the standing certificate
            // of that, rather than a distinction between rows.
            const above = line.edge >= 0.005
            return (
              <tr
                key={line.player_id}
                className="bg-surface transition-colors hover:bg-surface-2"
              >
                <td className="px-4 py-2 text-right font-mono text-fg-tertiary">{idx + 1}</td>
                <td className="px-4 py-2 font-medium text-fg">{line.player_name}</td>
                <td className="px-4 py-2 text-right font-mono tabular-nums text-fg">
                  {formatPct(line.model_prob)}
                </td>
                <td className="px-4 py-2 text-right font-mono tabular-nums text-fg-secondary">
                  {formatPct(line.implied_prob)}
                </td>
                <td className="px-4 py-2 text-right font-mono tabular-nums text-fg">
                  {formatAmerican(line.american_odds)}
                </td>
                <td className="px-4 py-2">
                  <span
                    className="rounded-full bg-fg-tertiary/15 px-1.5 py-0.5 text-[10px] font-medium text-fg-secondary"
                    title="Priced against a real sportsbook consensus from DataGolf, with vig removed."
                  >
                    Book
                  </span>
                </td>
                <td
                  className={`px-4 py-2 text-right font-mono tabular-nums font-semibold ${
                    above ? 'text-positive' : 'text-negative'
                  }`}
                >
                  {formatEdge(line.edge)}
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Reliability note — honest, per-market framing of how much to trust the edge
// ---------------------------------------------------------------------------

function ReliabilityNote({
  outcomeKey,
  lines,
}: {
  outcomeKey: OutcomeKey
  lines: BettingLine[]
}) {
  const base = OUTCOME_RELIABILITY[outcomeKey]

  // Coverage drives the badge, not the board-level `odds_source` flag, which
  // reads "datagolf" as soon as a single line is real and so overstated a
  // mostly-synthetic market as "Live odds · best market".
  const { real, total } = priceCoverage(lines)
  const allSynthetic = real === 0
  const allReal = total > 0 && real === total

  // A market the hardcoded map calls synthetic is promoted only on the strength
  // of actual coverage, and only as far as the coverage justifies.
  const tier = allSynthetic ? 'synthetic' : base.tier === 'synthetic' ? 'medium' : base.tier

  const coverage = allSynthetic
    ? 'No player in this market has a sportsbook price, so there is nothing to compare the board against and nothing is shown below.'
    : allReal
      ? `All ${total} lines are priced against a live sportsbook consensus, with vig removed.`
      : `${real} of ${total} lines are priced against a live sportsbook consensus. The remaining ${total - real} have no sportsbook price — with no market price there is no disagreement to measure, so they are left out of the comparison entirely rather than shown against a price generated from the board's own number.`

  const style = allSynthetic
    ? 'border-negative/30 bg-negative/5 text-fg-secondary'
    : tier === 'medium'
      ? 'border-accent/30 bg-accent/5 text-fg-secondary'
      : 'border-negative/30 bg-negative/5 text-fg-secondary'
  const badge = allSynthetic
    ? { label: 'Synthetic odds', cls: 'bg-negative/15 text-negative' }
    : tier === 'medium'
      ? {
          label: allReal ? 'Live odds' : 'Partial live odds',
          cls: 'bg-accent/15 text-accent',
        }
      : { label: 'Low confidence', cls: 'bg-negative/15 text-negative' }

  return (
    <div className={`rounded-lg border px-4 py-3 text-xs ${style}`}>
      <div className="flex items-center gap-2">
        <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${badge.cls}`}>
          {badge.label}
        </span>
        <span className="font-medium text-fg">{OUTCOME_LABELS[outcomeKey]} market</span>
      </div>
      <p className="mt-1.5 leading-relaxed">{coverage}</p>
      {/* The per-market note is a hardcoded assumption. Where live coverage
          contradicts it — make-cut is described there as having no sportsbook
          market at all — the measured coverage above wins and the stale
          sentence is dropped rather than printed beside it. */}
      {!allSynthetic && base.tier !== 'synthetic' && (
        <p className="mt-1 leading-relaxed">{base.note}</p>
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export function BettingEdge() {
  // Opens on Top 20 rather than Make Cut. Now that a player without a book
  // price is dropped instead of blanked, a market the books are not offering
  // renders an empty page — and DataGolf returns no make-cut prices at all at a
  // no-cut event (the FedExCup playoffs, the TOUR Championship). Top 20 is the
  // market the reliability map rates highest on live coverage, so the page
  // opens on something to read. Make Cut stays one click away.
  const [outcomeKey, setOutcomeKey] = useState<OutcomeKey>('top_20_prob')
  // Default to ≥10% so the table opens on meaningful divergences, not longshot noise.
  const [minProb, setMinProb] = useState<number>(0.1)

  const { data: currentTournament, isLoading: tournamentLoading } = useCurrentTournament()
  const tournamentId = currentTournament?.id ?? null

  const {
    data: board,
    isLoading: boardLoading,
    isError,
    error,
  } = useBettingEdge(tournamentId, outcomeKey)

  // Drop every player the books have not priced, apply the minimum-probability
  // filter, then sort by the size of the disagreement. A fabricated price is a
  // function of the served probability itself, so a row built on one is not a
  // comparison between two sources — it is the board's own number twice. There
  // is nothing to show, so it is not shown.
  const comparableLines = useMemo(() => {
    if (!board) return []
    return board.lines
      .filter(isRealPrice)
      .filter((l) => l.model_prob >= minProb)
      .sort((a, b) => b.edge - a.edge)
  }, [board, minProb])

  // How many players the market simply does not price, stated beneath the table
  // so their absence is visible rather than silent.
  const unpricedCount = board ? board.lines.length - board.lines.filter(isRealPrice).length : 0

  // Whether the books are offering this market at all, which is a different
  // empty state from "your filter is too tight" and reads differently below.
  const marketHasPrices = board ? board.lines.some(isRealPrice) : false

  // Compute max absolute edge for chart scale.
  const maxEdge =
    comparableLines.length > 0 ? Math.max(...comparableLines.map((l) => Math.abs(l.edge))) : 0.1

  return (
    <main className="mx-auto max-w-6xl space-y-6 px-6 py-10">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight">Market Comparison</h1>
        {currentTournament && (
          <p className="mt-1 text-sm text-fg-secondary">
            {currentTournament.name} ·{' '}
            {new Date(currentTournament.start_date).toLocaleDateString()}
          </p>
        )}
        <p className="mt-2 text-xs leading-relaxed text-fg-tertiary">
          Where the served board diverges from the market — board probabilities vs. book-implied
          odds for the current field. This page reports the disagreement and stops there: nothing
          here grades whether these disagreements were ever right, so none of it is a
          recommendation. Under Path A most players are served DataGolf&rsquo;s own probabilities,
          so when the odds side is also a live DataGolf consensus, the divergence below is DataGolf
          against its own feed, not the in-house model against an independent market — the coverage
          note under the market picker states which case applies.
        </p>
        {board && (
          <div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-fg-tertiary">
            <span>
              Players compared: <span className="font-mono text-fg">{comparableLines.length}</span>
              {minProb > 0 && (
                <span className="text-fg-tertiary"> (≥{Math.round(minProb * 100)}% filter)</span>
              )}
            </span>
          </div>
        )}
      </header>

      {(tournamentLoading || boardLoading) && (
        <p className="text-fg-secondary">Loading lines…</p>
      )}

      {!tournamentLoading && currentTournament == null && (
        <p className="text-fg-secondary">No active tournament found.</p>
      )}

      {isError && (
        <p className="text-negative">
          Error: {error instanceof Error ? error.message : 'Unknown failure'}
        </p>
      )}

      {board && (
        <>
          {/* Market selector — ordered by validated skill (Make Cut → … → Win) */}
          <section className="space-y-2">
            <p className="text-xs font-medium uppercase tracking-wider text-fg-tertiary">Market</p>
            <MarketPicker value={outcomeKey} onChange={setOutcomeKey} />
          </section>

          {/* Honest reliability caveat — this page reports a divergence between
              two sources and grades nothing, so the reader needs to know how
              much of the market is actually priced. Coverage is read from the
              unfiltered board so the note describes the market rather than
              whatever the probability filter currently admits. */}
          <ReliabilityNote outcomeKey={outcomeKey} lines={board.lines} />

          {/* Minimum board-probability filter — drops longshot noise from the view. */}
          <section className="space-y-2">
            <p className="text-xs font-medium uppercase tracking-wider text-fg-tertiary">
              Min. board probability
            </p>
            <ProbabilityFilter value={minProb} onChange={setMinProb} />
            <p className="text-[11px] italic text-fg-tertiary">
              Raising the threshold drops longshots from the view. A divergence on a player the
              board gives a low probability is mostly noise in both directions.
            </p>
          </section>

          {/* Two different kinds of nothing, which used to collapse into one
              message about the probability filter. "The books aren't offering
              this market" is not the reader's filter being too tight, and
              telling them to lower it would send them looking for data that
              does not exist this week. */}
          {!marketHasPrices ? (
            <p className="rounded-lg border border-warning/30 bg-warning/5 px-4 py-6 text-center text-sm text-fg-secondary">
              The books are not offering this market for {board.tournament_name}, so there is no
              sportsbook price to compare the board against and nothing is shown. This is normal at
              a no-cut event. Pick another market above.
            </p>
          ) : comparableLines.length === 0 ? (
            <p className="rounded-lg border border-negative/30 bg-negative/5 px-4 py-6 text-center text-sm text-fg-secondary">
              No priced player meets the ≥{Math.round(minProb * 100)}% board-probability threshold
              for this market. Lower the filter to see more players.
            </p>
          ) : (
            <>
              {/* Divergence chart — every plotted player has a real book price. */}
              <section className="space-y-3">
                <p className="text-xs font-medium uppercase tracking-wider text-fg-tertiary">
                  Largest divergences (top 20)
                </p>
                <div className="overflow-x-auto rounded-lg border bg-surface p-4">
                  <EdgeBarChart lines={comparableLines} maxEdge={maxEdge} />
                </div>
              </section>

              {/* Full table */}
              <section className="space-y-3">
                <p className="text-xs font-medium uppercase tracking-wider text-fg-tertiary">
                  All priced players, by divergence (high → low)
                </p>
                <LinesTable lines={comparableLines} />
                {/* The hidden players are stated rather than silently dropped:
                    a reader comparing this against the leaderboard's field size
                    should be able to account for the difference. */}
                {unpricedCount > 0 && (
                  <p className="text-[11px] italic text-fg-tertiary">
                    {unpricedCount} player{unpricedCount === 1 ? '' : 's'} in this field
                    {unpricedCount === 1 ? ' has' : ' have'} no sportsbook price and{' '}
                    {unpricedCount === 1 ? 'is' : 'are'} not shown. With no market price there is no
                    disagreement to measure.
                  </p>
                )}
              </section>
            </>
          )}
        </>
      )}
    </main>
  )
}
