"""initial schema

Revision ID: 808b57c7b9d5
Revises: 
Create Date: 2026-06-03 16:26:01.644133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808b57c7b9d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('par', sa.SmallInteger(), nullable=False),
    sa.Column('yardage', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.Enum('parkland', 'links', 'desert', 'mountain', 'stadium', 'resort', name='course_type'), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.CheckConstraint('par BETWEEN 68 AND 73', name=op.f('ck_courses_par_range')),
    sa.CheckConstraint('yardage BETWEEN 5000 AND 8500', name=op.f('ck_courses_yardage_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dg_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('turned_pro', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('dg_id', name=op.f('uq_players_dg_id'))
    )
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('purse', sa.BigInteger(), nullable=True),
    sa.Column('field_strength', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('upcoming', 'in_progress', 'completed', name='tournament_status'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_tournaments_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments'))
    )
    op.create_index(op.f('ix_tournaments_course_id'), 'tournaments', ['course_id'], unique=False)
    op.create_index(op.f('ix_tournaments_season'), 'tournaments', ['season'], unique=False)
    op.create_index(op.f('ix_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.create_table('betting_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=50), nullable=False),
    sa.Column('market', sa.Enum('win', 'top_5', 'top_10', 'top_20', 'make_cut', 'miss_cut', name='market_kind'), nullable=False),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_betting_lines_player_id_players')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_betting_lines_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_betting_lines'))
    )
    op.create_index('ix_betting_lines_t_p_m_b', 'betting_lines', ['tournament_id', 'player_id', 'market', 'book_name'], unique=False)
    op.create_index(op.f('ix_betting_lines_tournament_id'), 'betting_lines', ['tournament_id'], unique=False)
    op.create_table('tournament_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'made_cut', 'missed_cut', 'withdrew', 'disqualified', name='entry_status'), nullable=False),
    sa.Column('final_position', sa.SmallInteger(), nullable=True),
    sa.Column('final_score_to_par', sa.SmallInteger(), nullable=True),
    sa.Column('official_money_cents', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_tournament_entries_player_id_players')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_entries_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_entries')),
    sa.UniqueConstraint('tournament_id', 'player_id', name='tournament_player')
    )
    op.create_index('ix_tournament_entries_tournament_id_player_id', 'tournament_entries', ['tournament_id', 'player_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('score_to_par', sa.SmallInteger(), nullable=False),
    sa.Column('tee_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sg_ott', sa.Float(), nullable=False),
    sa.Column('sg_app', sa.Float(), nullable=False),
    sa.Column('sg_arg', sa.Float(), nullable=False),
    sa.Column('sg_putt', sa.Float(), nullable=False),
    sa.Column('sg_t2g', sa.Float(), nullable=False),
    sa.Column('sg_total', sa.Float(), nullable=False),
    sa.Column('driving_distance_avg', sa.Float(), nullable=True),
    sa.Column('fairways_hit', sa.SmallInteger(), nullable=True),
    sa.Column('gir', sa.SmallInteger(), nullable=True),
    sa.Column('putts', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('round_number BETWEEN 1 AND 4', name=op.f('ck_rounds_round_number_range')),
    sa.ForeignKeyConstraint(['entry_id'], ['tournament_entries.id'], name=op.f('fk_rounds_entry_id_tournament_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds')),
    sa.UniqueConstraint('entry_id', 'round_number', name='entry_round_number')
    )
    op.create_index(op.f('ix_rounds_entry_id'), 'rounds', ['entry_id'], unique=False)
    op.create_index(op.f('ix_rounds_tee_time'), 'rounds', ['tee_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rounds_tee_time'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_entry_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index('ix_tournament_entries_tournament_id_player_id', table_name='tournament_entries')
    op.drop_table('tournament_entries')
    op.drop_index(op.f('ix_betting_lines_tournament_id'), table_name='betting_lines')
    op.drop_index('ix_betting_lines_t_p_m_b', table_name='betting_lines')
    op.drop_table('betting_lines')
    op.drop_index(op.f('ix_tournaments_status'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_season'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_course_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###

    # Postgres ENUM types are objects in their own right and persist beyond
    # the tables that use them. Drop them explicitly so a downgrade-upgrade
    # cycle doesn't fail with "type already exists".
    for type_name in (
        "course_type",
        "entry_status",
        "market_kind",
        "tournament_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))
